# Força o uso do termo "xterm-256color" ou "kitty" para melhor compatibilidade
term xterm-256color

# Habilita suporte a mouse dentro do tmux
mouse_hide_wait 3.0
enable_audio_bell no

# Executa neofetch na inicialização
# startup_session ~/.config/kitty/startup.conf

# Tira confirmação de fechamento quando algo esta rodando no terminal
# confirm_os_window_close 1 # 0 para nao confirmar

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
